# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Job1
    steps:
    - script: echo Hello, world! job1
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo Mais Informação
      displayName: 'Run a multi-line script'
  - job: Job2
    dependsOn: Job1
    steps:
    - script: echo HELLO, Hello, JOB2!
      displayName: 'Run a one-line JOB2 script'
  - job: Job3
    dependsOn: Job2
    steps:
    - script: |
        echo "Hello, JOB3!"
      displayName: 'Run a multi-line Job3 script'