trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build Job1
    - bash: echo $(pipelineLevelVariable)
  - job: Job2
    steps:
    - bash: echo Build Job2
# - stage: devdeploy
#   variables:
#     environment: dev
#   dependson: build
#   jobs:
#   - job: devdeployjob
#     steps:
#     - bash: echo $(environment)deploy job
# - stage: qadeploy
#   dependson: build
#   jobs:
#   - job: qadeployjob
#     steps:
#     - bash: echo qa deploy job
# - stage: proddeploy
#   jobs:
#   - job: proddeployjob
#     steps:
#     - bash: echo prod deploy job
