trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the Build"
- stage: DevDeploy
  jobs:
  - job: DevJob
    steps:
    - bash: echo "Considerar apenas o job tipo deployment"
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QA
